#!/bin/bash

# You need MatLab and Questasim first

git fetch upstream
git merge upstream/master
HOME_DIR=`pwd`

BUILD_DIR=${HOME_DIR}/build
cd ${BUILD_DIR}

make -j4

# If the installation doesn't work, you need to remove ConstraintProgrammingEngine.* in src/schedule. And remove the include "ConstraintProgrammingEngine.hpp" in Scheduler.hpp
