#!/bin/bash

FIMP_NAME=$1

PROJECT_HOME=`pwd`
FIMP_HOME=${PROJECT_HOME}/../../..
DIMARCH_DUMP_HOME=${PROJECT_HOME}/output/dimarch_dump
SRC_HOME=${PROJECT_HOME}/output/source
TEST=${FIMP_HOME}/test/Test/test.py
SRC=${FIMP_NAME}_1.m
MATLAB=matlab
PYTHON=python
DIMARCH_DUMP=dimarch_dump
TRANS_DIMARCH_TO_NUMPY=transDim2Np
DIMARCH_DUMP_FILE=${DIMARCH_DUMP_HOME}/dimarch_dump.json
DNN_INFO_FILE=${PROJECT_HOME}/dnn_info.json
DIM2NP_FILE=${DIMARCH_DUMP_HOME}/numpy_dimarch.json

make clean;
make || { echo 'FIMP build Error...' ; exit 1; };
make sim || { echo 'Simulation Error...' ; exit 1; };
mkdir ${DIMARCH_DUMP_HOME};
cd ${SRC_HOME};
${DIMARCH_DUMP} -o ${DIMARCH_DUMP_HOME} ${SRC};
cd ${DIMARCH_DUMP_HOME};
${MATLAB} -nosplash -nodesktop -r "try, dimarch_${FIMP_NAME}_1_dump; end, quit; exit;" &> /dev/null || { echo 'dimarch dump failed' ; exit 1; };
cd ${PROJECT_HOME};
${TRANS_DIMARCH_TO_NUMPY} --dump=${DIMARCH_DUMP_FILE} --dnn=${DNN_INFO_FILE} -o ${DIM2NP_FILE} || { echo 'Translate Dimarch result to Numpy Error...' ; exit 1; };
${PYTHON} ${TEST} --fimp=${PROJECT_HOME}
